-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:09:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `capacitacao` ;

-- -----------------------------------------------------
-- Table `mydb`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`instrutor` (
  `id_instrutor` 				INT NOT NULL,
  `Nome` 						VARCHAR(100) NOT NULL,
  `Email` 						VARCHAR(100) NOT NULL,
  `Valor_hora` 					DOUBLE NOT NULL,
  `Certificado` 				VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_instrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`curso` (
  `id_curso` 				INT NOT NULL,
  `Nome` 					VARCHAR(100) NOT NULL,
  `Requisito` 				VARCHAR(100) NOT NULL,
  `cursocol` 				VARCHAR(45) NOT NULL,
  `Carga_horaria` 			DOUBLE NOT NULL,
  `Preco` 					DOUBLE NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`turma` (
  `id_turma` 				INT NOT NULL,
  `Carga_horaria` 			DOUBLE NOT NULL,
  `Data_inicial` 			DATE NOT NULL,
  `Data_final` 				DATE NOT NULL,
  `instrutor_id_instrutor` 	INT NOT NULL,
  `curso_id_curso` 			INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  -- INDEX `fk_turma_instrutor_idx` (`instrutor_id_instrutor` ASC) VISIBLE,
  -- INDEX `fk_turma_curso1_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turma_instrutor`
    FOREIGN KEY (`instrutor_id_instrutor`)
    REFERENCES `capacitacao`.`instrutor` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `capacitacao`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`aluno` (
  `id_aluno` 				INT NOT NULL,
  `Nome` 					VARCHAR(100) NOT NULL,
  `CPF` 					VARCHAR(15) NOT NULL,
  `DataNasc` 				DATE NOT NULL,
  `Fone` 					CHAR(14) NOT NULL,
  `Email` 					VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`matricula` (
  `id_matricula` 			INT NOT NULL,
  `Data_matricula` 			DATE NOT NULL,
  `aluno_id_aluno` 			INT NOT NULL,
  `turma_id_turma` 			INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  -- INDEX `fk_matricula_aluno1_idx` (`aluno_id_aluno` ASC) VISIBLE,
  -- INDEX `fk_matricula_turma1_idx` (`turma_id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `capacitacao`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `capacitacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
