-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:43:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda` DEFAULT CHARACTER SET utf8 ;
USE `venda` ;

-- -----------------------------------------------------
-- Table `venda`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`categoria` (
  `idcategorias` 		INT NOT NULL,
  `dscategoria` 		VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`produto` (
  `idprodutos` 			INT NOT NULL,
  `dsproduto` 			VARCHAR(45) NOT NULL,
  `preco` 				FLOAT NOT NULL,
  `qtdade` 				INT NOT NULL,
  `foto` 				LONGBLOB NOT NULL,
  `categoria_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  -- INDEX `fk_produto_categoria_idx` (`categoria_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_idcategorias`)
    REFERENCES `venda`.`categoria` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`cliente` (
  `idcliente` 				INT NOT NULL,
  `nome` VARCHAR(100) 		NOT NULL,
  `email` VARCHAR(100)		 NOT NULL,
  `senha` VARCHAR(100) 		NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`pedido` (
  `idpedido` 			INT NOT NULL,
  `data` 				DATE NOT NULL,
  `status` VARCHAR(45) 	NOT NULL,
  `sessao` VARCHAR(45) 	NOT NULL,
  `cliente_idcliente` 	INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  -- INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `venda`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`pedidoItens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`pedidoItens` (
  `idpedidoItens` 		INT NOT NULL,
  `qtdade` 				INT NOT NULL,
  `preco` 				FLOAT NOT NULL,
  `total` 				FLOAT NOT NULL,
  `produto_idprodutos` 	INT NOT NULL,
  `pedido_idpedido` 	INT NOT NULL,
  PRIMARY KEY (`idpedidoItens`),
  -- INDEX `fk_pedidoItens_produto1_idx` (`produto_idprodutos` ASC) VISIBLE,
  -- INDEX `fk_pedidoItens_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidoItens_produto1`
    FOREIGN KEY (`produto_idprodutos`)
    REFERENCES `venda`.`produto` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoItens_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `venda`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
